### ISSUE TITLE
Removal of input files

### ISSUE THREAD

**Issue by xnacly** [daniel0611/AdventOfCode2022#1]
The creators of aoc ask everyone to not commit their inputs: https://www.reddit.com/r/adventofcode/comments/zh2hk0/2022friendly_reminder_dont_commit_your_input/

**Comment by hlxid** [comment]
Thanks for the notice. The inputs are now encrypted inside the git repository with 35cabdc485c0ebfd70da5e112ab76357e1d97a34 and the un-encrypted versions have been removed from the git history.
